services:
    traction.handler:
        class: Traction\Handler
        arguments:
            -
                host:        "%noetix_traction.host%"
                user_id:     "%noetix_traction.user_id%"
                password:    "%noetix_traction.password%"
                endpoint_id: "%noetix_traction.endpoint_id%"

    traction.dynamic:
        class: Traction\DynamicHandler
        arguments:
            -
                connection:  "%noetix_traction.connection%"
                password:    "%noetix_traction.password%"